### PR TITLE
Add missing Lap intensity values

### LINKED ISSUE #38: Missing Lap intensity values
Currently `intensity` field in laps is mapped to 4 values: `active`, `rest`, `warmup` and `cooldown`. There are another 3 values ([source](https://developer.garmin.com/fit/file-types/workout/)):
image

Currently those values are parsed to `undefined`.

I prepared a PR https://github.com/jimmykane/fit-parser/pull/39.

### PR DESCRIPTION
**Pull request by michal-grzelak**
Closes https://github.com/jimmykane/fit-parser/issues/38

This PR will add 3 new intensity values as described in https://github.com/jimmykane/fit-parser/issues/38.
- recovery
- interval
- other

### CODE REVIEW

**Review by krzysztof-cislo — APPROVED** [review]
@jimmykane can you please release new version when you merge this PR?

**Comment by jimmykane** [comment]
Sure. Please give me the weekend time. Will get on this Monday as I am
traveling

**Comment by krzysztof-cislo** [comment]
> Sure. Please give me the weekend time. Will get on this Monday as I am traveling

Sure. Thank you!

**Comment by jimmykane** [comment]
@krzysztof-cislo  done via 1.20.0

**Comment by krzysztof-cislo** [comment]
Again, thank you very much @jimmykane !

**Pull request merged**
